services:
  mochitto:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
      - ./auth.json:/app/auth.json
      - ./logs:/app/logs
    depends_on:
      - voicevox
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  voicevox:
    image: voicevox/voicevox_engine:cpu-latest
    ports:
      - "50021:50021"
    restart: unless-stopped
